# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_tor',
                'doc_host': 'https://Xueyuan33.github.io',
                'git_url': 'https://github.com/Xueyuan33/nbdev_tor',
                'lib_path': 'nbdev_tor'},
  'syms': {'nbdev_tor.core': {'nbdev_tor.core.foo': ('core.html#foo', 'nbdev_tor/core.py')}}}
